## 开发/测试/生产环境分别对应dev/test/prod，可以自由定义
spring:
  profiles:
    active: dev
mq:
  info[0]:
    mqname: "测试1"
    username: "test1"
    password: ""
    hostname: ""
  info[1]:
    mqname: "测试2"
    username: "test2"
    password: ""
    hostname: ""

